version: '3.8'

services:
  next-app:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: 
      - node 
      - --inspect=0.0.0.0:9229
      - ./node_modules/next/dist/bin/next 
      - dev 

  npm:
    image: node:18-alpine
    volumes:
       - .:/app
    working_dir: /app
